# Site
name: 'دفعة الطب البشري 2022'
description: 'دفعة الطب البشري 2022'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/med2022'
disqus: 'quraish-ga'
email: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Admin
      site:           
      avatar:         assets/images/admin.png
      bio:            ---
      email:          
      twitter:        
    hamza:
      name:           حمزة مرزوق
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/h.jpeg
      bio:            طالب طب بشري في جامعة العلوم والتكنولوجيا الأردنية
      email:          ايميل محظور
      twitter:        https://www.instagram.com/hmz_common_w/
    abdul:
      name:           عبدالله الدالاتي
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/abdul.jpeg
      bio:            طالب طب بشري في جامعة العلوم والتكنولوجيا الأردنية
      email:          ايميل محظور
      twitter:        https://www.instagram.com/abdullah_aldalati/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hamza
      avatar: assets/images/h.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
